import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddOnDeleteCascadeToItemAccountIdFK1762823568908 implements MigrationInterface {
    name = 'AddOnDeleteCascadeToItemAccountIdFK1762823568908';

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Drop old FK
        await queryRunner.query(`
            ALTER TABLE "item"
            DROP CONSTRAINT "FK_f8e90c90aea7e57bd474170f35b"
        `);

        // Add new FK with cascade using a clean name
        await queryRunner.query(`
            ALTER TABLE "item"
            ADD CONSTRAINT "FK_item_account_id"
            FOREIGN KEY ("account_id") REFERENCES "account"("id")
            ON DELETE CASCADE
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Drop FK_item_account_id (cascade version)
        await queryRunner.query(`
            ALTER TABLE "item"
            DROP CONSTRAINT "FK_item_account_id"
        `);

        // Recreate original FK WITHOUT cascade using the autogenerated name
        await queryRunner.query(`
            ALTER TABLE "item"
            ADD CONSTRAINT "FK_f8e90c90aea7e57bd474170f35b"
            FOREIGN KEY ("account_id") REFERENCES "account"("id")
        `);
    }
}
