services:
  postgres-db:
    image: postgres:17.5-alpine
    restart: always        
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:      
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis-db:
    image: redis:8.0-alpine
    restart: always
    volumes:
      - redis:/data
    ports:
      - ${REDIS_PORT}:6379

volumes:
  redis: 
    external: false
  postgres:
    external: false
      