services:
  postgres:
    image: postgres:17.5-alpine
    container_name: postgres
    restart: always        
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:      
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    profiles:
      - dev

  redis:
    image: redis:8.0-alpine
    container_name: redis
    restart: always
    volumes:
      - redis:/data
    ports:
      - ${REDIS_PORT}:6379
    profiles:
      - dev

  postgres-test:
    image: postgres:17.5-alpine
    restart: always        
    tmpfs: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:      
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    profiles:
      - int

  redis-test:
    image: redis:8.0-alpine
    command: redis-server --appendonly no --save ""
    restart: always
    tmpfs: /data
    ports:
      - ${REDIS_PORT}:6379
    profiles:
      - int

volumes:
  redis: 
    name: rate-wise-redis
    external: false
  postgres:
    name: rate-wise-postgres
    external: false
  mailpit:
    name: rate-wise-mailpit
    external: false
      