services:
  mailpit:
    image: axllent/mailpit:v1.27.6     
    restart: always
  redis:
    image: redis:8.0-alpine    
    restart: always
  postgres:
    image: postgres:17.5-alpine          
    restart: always
  migrate:        
    restart: "no"
    build:
      context: ..
      target: development
    image: ratewise:dev
    command: sh -c "npx nest build && npx typeorm -d dist/db/data-source.js migration:run"    
    volumes:
      - ../db:/usr/src/app/db
    depends_on:
      postgres:
        condition: service_healthy        