export const PAGINATION_CACHE_QUEUE = 'CACHE_QUEUE';
export const PAGINATION_REPOSITORY = 'PAGINATION_REPOSITORY';
export const REPOSITORY_TOKEN = 'REPOSITORY_TOKEN';
export const TRANSFORM_FUNCTION = 'TRANSFORM_FUNCTION';
