name: Integration

on:
  pull_request:
    branches:
      - development

concurrency:
  group: integration-${{ github.ref }}
  cancel-in-progress: true        

jobs: 
  run-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.19.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        
      - name: Run integration tests
        run: npm run test:integration     
    