name: Integration Tests
on:
  pull_request:
    branches:
      - development

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true        

jobs: 
  call-linter:
    uses: ./.github/workflows/lint.yml

  run-integration-tests:    
    needs: call-linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.19.0'
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run Integration tests
        run: npm run test:integration     
    