name: Integration

on:
  pull_request:
    branches:
      - development

concurrency:
  group: integration-${{ github.ref }}
  cancel-in-progress: true       

jobs: 
  tests:
    name: Integration Tests    
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.19.0
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run Integration Tests
        run: npm run test:integration     
    
    