name: Lint

on:  
  pull_request:
    branches:
      - development      

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true        

permissions:
  checks: write
  contents: write

jobs:
  run-linter:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.19.0'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        uses: wearerequired/lint-action@v2
        with:
          continue_on_error: false
          eslint: true
          eslint_auto_fix: false
          eslint_args: "\"{src,apps,libs,test}/**/*.ts\" --max-warnings 0"          